### ISSUE TITLE
[버그] 선택된 날짜가 사라지지 않는 현상

### ISSUE THREAD

**Issue by anhahyoun** [boostcampwm-2021/android06-GagyeBoost#28]
### 재현
1. 날짜 선택 후 +버튼 눌러 addFragment화면으로 이동
2. X나 뒤로가기로 홈 화면으로 돌아감
3. 다른 일자를 선택 시 전에 있던 선택 화면이 없어지지 않음
<img src=https://user-images.githubusercontent.com/54823186/140258754-83a577f6-bb36-4bfb-a5fe-490890d57aa7.png width=40%>

**Comment by sus0985** [comment]
+ 버튼 누른 후 다시 돌아오게 되면 Adapter 객체가 다시 생성되면서 adapter 내에서 들고있던 현재 선택된 position 데이터가 사라지면서 문제가 발생했습니다!

그래서 CalendarAdapter를 onCreate 될 때 생성하도록 해서 문제는 해결됐습니다.

다른 방법으로는 viewModel에서 값을 들고 있도록 할 수 있는데 방법에 대해선 다음에 얘기해보면 좋을것 같습니다!!
