### ISSUE TITLE
[버그] 오늘 날짜 표시 버그

### ISSUE THREAD

**Issue by 7hong13** [boostcampwm-2021/android06-GagyeBoost#32]
### 현상
현재 달뿐만 아니라 이전 달 혹은 다음 달 날짜도 오늘 날짜와 겹칠시 회색 처리됨
![Screenshot_20211104-143651_GagyeBoost](https://user-images.githubusercontent.com/52355963/140263448-e4623252-361c-4a4c-8b81-3f7199609a87.png)

**Comment by anhahyoun** [comment]
DB에서 데이터 가져와서 DateItem에 month를 다르게 넣어줘도 다른 달에 회색 처리가 되나요?
(지금은 임시로 전부 2021년 11월로 넣어줘서 다른 월도 다르게 표시되는게 정상이긴해요..)
