### ISSUE TITLE
[버그] 수입/지출 추가 시 달력에 수입으로 표시

### ISSUE THREAD

**Issue by anhahyoun** [boostcampwm-2021/android06-GagyeBoost#40]
## 재현
1. +버튼 눌러 지출로 금액 추가
2. 홈 화면 상단에 수입으로 표시, 하단 상세 RecyclerView에 수입 색인 초록색으로 표시

<img src=https://user-images.githubusercontent.com/54823186/140507644-32a9b426-8e58-49b7-9284-5395da08d948.png width=40%>

**Comment by sus0985** [comment]
이 부분은 수입/지출에 대한 argument 전달되고 DB에 정상적으로 저장되면 해결될 부분이라 그대로 두겠습니다!
