### ISSUE TITLE
[버그] 지출/수입 추가 후 다시 추가 할 시 금액 data가 남아있음

### ISSUE THREAD

**Issue by anhahyoun** [boostcampwm-2021/android06-GagyeBoost#41]
## 재현
1. +버튼 눌러 금액 입력
2. 다시 +버튼을 눌러 지출/수입 화면으로 이동 시 이전 금액 남아있음
<img src=https://user-images.githubusercontent.com/54823186/140479469-578590fd-eed9-48e3-9af0-12a93b17f398.png width=40%>

**Comment by sus0985** [comment]
AddFragment의 onViewCreated 시점에 0으로 초기화하도록 하였습니다.
