### ISSUE TITLE
[버그] 지출/수입이 추가된 일자를 클릭 시 금액이 표시 되지 않음

### ISSUE THREAD

**Issue by anhahyoun** [boostcampwm-2021/android06-GagyeBoost#42]
## 재현
1. 지출/수입이 표시된 날짜를 클릭
2. 클릭 시 배경이 초록색으로 변경되면서 text가 보이지 않음
<img src=https://user-images.githubusercontent.com/54823186/140508154-c22b1e96-9a49-45b5-b370-e5052429c9b6.png width=40%>

**Comment by sus0985** [comment]
이 부분은 달력쪽에서 여러 문제가 겹쳐서 생기는 것같아서 당장 해결을 못하겠습니다 ㅠㅠ 월요일에 질문 드리겠습니다!
