### ISSUE TITLE
[버그] 지출/수입 추가 시 금액 입력할 때 커서가 앞으로 가는 현상

### ISSUE THREAD

**Issue by anhahyoun** [boostcampwm-2021/android06-GagyeBoost#44]
## 재현
1. +버튼 눌러 지출/수입 추가 화면 이동
2. 금액이 0일때 입력시 커서가 앞으로 이동함
![커서버그](https://user-images.githubusercontent.com/54823186/140513866-60928756-8d0b-40eb-b49b-58120788145e.gif)

## 위플가계부 예시

https://user-images.githubusercontent.com/54823186/140515119-d3e3826a-b2b4-4eef-abf4-46c36b8d6832.mp4

**Comment by sus0985** [comment]
생각 못했던 버그네요!

```kotlin=
binding.etWon.doAfterTextChanged {
            it?.let {
                if (it.length == 1) binding.etWon.setSelection(it.length)
            }
        }
```

Fragment에서 afterTextChanged로 설정했는데 이런 방식도 괜찮을까요?

**Comment by anhahyoun** [comment]
좋은 것 같아요! mp4가 왜 안보이는지는 모르겠지만
위플 가계부에서는 한 글자를 추가할 때마다 커서가 맨 뒤로 가요!
가운데 글자를 수정하면 수정 뒤 커서가 맨 뒤로 이동합니다.

**Comment by sus0985** [comment]
> 좋은 것 같아요! mp4가 왜 안보이는지는 모르겠지만 위플 가계부에서는 한 글자를 추가할 때마다 커서가 맨 뒤로 가요! 가운데 글자를 수정하면 수정 뒤 커서가 맨 뒤로 이동합니다.

오 처음에 수정했던게 입력할때마다 커서를 맨 뒤로 보내도록 했는데, 중간부분 수정하려고 할 때를 생각해서 바꿨습니다.
하현님 말씀하신대로 가운데 글자 수정시에도 뒤로 보내는게 나을까요?

**Comment by anhahyoun** [comment]
> 하현님 말씀하신대로 가운데 글자 수정시에도 뒤로 보내는게 나을까요?

이 부분은 어떻게 해도 상관 없을 것 같아요! 저는 중간 부분 수정 시 커서가 그대로 있어도 좋고 맨 뒤로 이동해도 좋아요 😀
