### ISSUE TITLE
[버그] 카테고리 추가 시 전에 있던 데이터 남아있는 버그

### ISSUE THREAD

**Issue by anhahyoun** [boostcampwm-2021/android06-GagyeBoost#45]
## 재현
1. 카테고리 선택 후 위치 화면에서 뒤로가기
2. 카테고리 추가 선택
3. 전에 선택한 카테고리 데이터가 남아있음

![카테고리 버그](https://user-images.githubusercontent.com/54823186/140525008-c2f0176f-d163-4810-9fbb-65e5bc3dc918.gif)

**Comment by kim0hoon** [comment]
와 버그제보 감사합니다
백버튼 누를 때 리셋해야 하는걸 생각도 못했었네요
주석 친 부분 추가하니 해결됐습니다
![image](https://user-images.githubusercontent.com/14107670/140611102-3d49a827-a7fc-42d4-9608-a4bffcb068c1.png)
