### ISSUE TITLE
[달력] 첫주 목요일까지만 지출/수입 내역 보였다 안보였다 하는 현상

### ISSUE THREAD

**Issue by 7hong13** [boostcampwm-2021/android06-GagyeBoost#83]
- 첫 주 목요일까지의 itemView에서 내역이 사라지는 현상

**Comment by kim0hoon** [comment]
해결은 한 거 같은데 원인을 모르겠네요
일단 11월 1,2,3,4의 수입, 지출 TextView가 gone상태로 바뀌어있었어요

![image](https://user-images.githubusercontent.com/14107670/141253008-3f95fbc5-699b-4f03-a283-90f63a1ff3d7.png)
