### ISSUE TITLE
[지도] 필터 레이아웃 width

### ISSUE THREAD

**Issue by kim0hoon** [boostcampwm-2021/android06-GagyeBoost#93]
![image](https://user-images.githubusercontent.com/14107670/141242435-c0f1dacb-f7a9-42b3-a5e5-321c36c212ae.png)
![image](https://user-images.githubusercontent.com/14107670/141242465-ced6a975-ffc7-4249-bd08-2edd06511962.png)

**Comment by anhahyoun** [comment]
이거 제가 해결했어요! 미리 말했어야 하는데 죄송해요ㅜㅜ
